### PR TITLE
Adds Matomo Analytics App

### PR DESCRIPTION
**Pull request by compgeniuses**
Repositiory here: https://github.com/compgeniuses/ns8-matomo

Installing the App
`add-module ghcr.io/compgeniuses/matomo:latest 1`

### CODE REVIEW

**Comment by compgeniuses** [comment]
@stephdl could you kindly review this

**Comment by stephdl** [comment]
same as others, I would like that yo test the app in the community before to ask to be added here

**Comment by compgeniuses** [comment]
Community reference is here: https://community.nethserver.org/t/ns8-matomo-module/22835

IT Would be easier if you saw specific test cases that needs to be worked or improved upon.

The community can only test as much. Laylow and danb have tested, as well as internally

**Comment by stephdl** [comment]
released in genius repository

**Pull request closed without merging**
