### PR TITLE
Adds N8n App

### PR DESCRIPTION
**Pull request by compgeniuses**
Adds N8n App here: https://github.com/compgeniuses/ns8-n8n

### CODE REVIEW

**Comment by compgeniuses** [comment]
@stephdl could you kindly review this

**Comment by stephdl** [comment]
Please before to consume time of developer, could you ask to the community to fully test your app, after the first QA, then we could imagine to review

**Comment by compgeniuses** [comment]
I Appreciate your Sentiments and concerns, I apologize.

There are cases for Apps that not everyone in the community would be able to test, especially at the moment since NS8 is still young.

How should this kind of case be treated and handled?

My understanding was, once an app is built and announced, after community testing, Should be submitted to Nethforge for distribution, the dev team would look into the app, and if something out of the norm spotted, Feedback would be provided to help improve the app.

In future maybe the community will get better at testing apps and should reduce the testing time out of your hand.

**Comment by stephdl** [comment]
released in genius repository

**Pull request closed without merging**
